export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const REGISTER_ORGANIZER_REQUEST = 'REGISTER_ORGANIZER_REQUEST'
export const REGISTER_ORGANIZER_SUCCESS = 'REGISTER_ORGANIZER_SUCCESS'
export const REGISTER_ORGANIZER_FAIL = 'REGISTER_ORGANIZER_FAIL'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL'